- name: node exporter stop and disable
  systemd:
    name: node_exporter
    state: stopped
    enabled: no

- name: rm files
  file:
    path: "{{ item }}"
    force: yes
    state: absent
  with_items:
    - /etc/systemd/system/node_exporter.service
    - /usr/local/bin/node_exporter

- name: rm recurse
  file:
    path: /var/lib/node_exporter
    force: yes
    state: absent

- name: daemon reload
  systemd:
    name: daemon-reload
    daemon_reload: yes

- name: remove group
  group:
    name: "{{ _node_exporter_system_group }}"
    state: absent

- name: remove user
  user:
    name: "{{ _node_exporter_system_user }}"
    remove: yes
    force: yes
