- name: docker install
  shell: curl -Ssl "https://get.docker.com" | sh

- name: copy daemon.json
  template:
    src: templates/daemon.json.j2
    dest: /etc/docker/daemon.json

- name: systemctl daemon-reload
  command: systemctl daemon-reload

- name: service_facts
  service_facts:

- debug:
  var: ansible_facts.services['docker.service']['state']

- name: restart docker
  service:
    name: docker
    state: restarted
  failed_when: ansible_facts.services['docker.service']['state']=="stopped"