apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    name: helm-loader
  annotations:
    strategy.spinnaker.io/recreate: "true"
spec:
  activeDeadlineSeconds: {{ .Values.activeDeadlineSeconds }}
  template:
    metadata:
      name: {{ .Chart.Name }}
    spec:
      {{- if .Values.securityContext.enable }}
      securityContext:
        runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
        runAsUser: {{ .Values.securityContext.runAsUser | int64 }}
        fsGroup: {{ .Values.securityContext.fsGroup | int64 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{.Chart.Name}}
        image: {{.Values.image.repository}}
        command: [
          "sh", "-c",
          "printenv && helm_loader pull -H $PULL_URL -c /tmp/ -u $USERNAME -p $PASSWORD && helm_loader push -H $PUSH_URL -c /tmp/ -u $USERNAME -p $PASSWORD"]
        envFrom:
        - secretRef:
            name: secret-helm-update
      restartPolicy: Never
