---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: default
  namespace: dev-sig
spec:
  hard:
    limits.cpu: "2"
    limits.memory: 2Gi
    requests.cpu: 550m
    requests.memory: 2Gi

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: default
  namespace: qa-sig
spec:
  hard:
    limits.cpu: "2"
    limits.memory: 2Gi
    requests.cpu: 550m
    requests.memory: 2Gi


---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: default
  namespace: sandbox-sig
spec:
  hard:
    limits.cpu: "2"
    limits.memory: 2Gi
    requests.cpu: 550m
    requests.memory: 2Gi

