---
resource_types:

- name: concourse-bitbucket-pullrequest
  type: docker-image
  source:
    username: ((registry_user))
    password: ((registry_password))
    repository: docker.fabric8.ru/devops/concourse-bitbucket-pullrequest-resource

- name: bitbucket-build-status
  type: docker-image
  source:
    repository: ((docker_proxy))/shyxormz/bitbucket-build-status-resource

- name: git-multibranch
  type: docker-image
  source:
    username: ((registry_user))
    password: ((registry_password))
    repository: docker.fabric8.ru/devops/git-multibranch-resource

resources:

  - name: source-code-master
    type: git-multibranch
    check_every: 1m
    source:
      uri: ssh://git@((bitbucket_host)):7999/((project_prefix))/((project_name)).git
      private_key: ((git_private_key))
      branch: 'master'
      paths:
        - .scripts/

  - name: git_ns-quotas
    type: git
    source:
      uri: http://((bitbucket_host))/scm/((project_prefix))/((project_name)).git
      branch: 'master'
      username: ((bitbucket_username))
      password: ((bitbucket_password))
      ignore_paths:
        - .ci/
        - .scripts/

  - name: pullrequest
    type: concourse-bitbucket-pullrequest
    source:
      password: ((bitbucket_password))
      uri: https://((bitbucket_host))/scm/((project_prefix))/((project_name)).git
      username: ((bitbucket_username))

  - name: ci
    type: git
    source:
      uri: http://((bitbucket_host))/scm/((project_prefix))/((project_name)).git
      branch: 'master'
      username: ((bitbucket_username))
      password: ((bitbucket_password))
      paths:
        - .ci/

  - name: build_status
    type: bitbucket-build-status
    source:
      username: ((bitbucket_username))
      password: ((bitbucket_password))
      endpoint: ((bitbucket_url))

jobs:

  - name: check pullrequest
    plan:
      - get: pullrequest
        trigger: true

      - get: source-code-master

      - put: pullrequest
        params:
          path: pullrequest
          status: pending

      - task: check pullrequest
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              username: ((registry_user))
              password: ((registry_password))
              repository: docker.fabric8.ru/devops/k8s-toolkit
              tag: 'latest'
          run:
            path: sh
            args:
            - -ec
            - |
              source-code-master/.scripts/validate-yaml.sh pullrequest/dc &&
              source-code-master/.scripts/validate-yaml.sh pullrequest/dccs

          inputs:
          - name: pullrequest
          - name: source-code-master

        on_failure:
          put: pullrequest
          params:
            path: pullrequest
            status: failure

        on_success:
          put: pullrequest
          params:
            path: pullrequest
            status: success

  - name: Update quotas
    on_success:
      put: build_status
      params:
        build_status: SUCCESSFUL
        repository: git_ns-quotas

    on_failure:
      put: build_status
      params:
        build_status: FAILED
        repository: git_ns-quotas
    plan:
      - get: git_ns-quotas
        trigger: true
      - get: source-code-master

      - task: "Update NS quotas"
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              username: ((registry_user))
              password: ((registry_password))
              repository: docker.fabric8.ru/devops/k8s-toolkit
              tag: 'latest'
          run:
            path: sh
            args:
              - -ec
              - |
                source-code-master/.scripts/apply-file.sh git_ns-quotas/dc &&
                source-code-master/.scripts/apply-file.sh git_ns-quotas/dccs
          inputs:
          - name: git_ns-quotas
          - name: source-code-master

  - name: Apply new pipeline
    plan:
      - get: ci
        trigger: true

      - set_pipeline: self
        file: ci/.ci/pipeline.yaml